In [4]:
from torch_geometric.data import Data
from utils import create_pointer_graph
import numpy as np 
import torch

In [23]:
edges = [[0, 1, 1, 2, 2, 2, 3, 4],
         [1, 0, 2, 1, 3, 4, 2, 2]]
edges = torch.tensor(edges)
x = torch.zeros(5, 2, 1)+0.5
graph = Data(x=x, edge_index=edges)
pg = create_pointer_graph(graph)
pg

[([1], [1]), ([0, 2], [0, 2]), ([1, 3, 4], [1, 3, 4]), ([2], [2]), ([2], [2])]

In [79]:
psi = torch.zeros(graph.num_nodes, graph.num_nodes, 2, 2)
fi = torch.zeros(graph.num_nodes, graph.num_nodes, 2, 2)
psi[0, 1] = psi[2, 3] = torch.tensor([[1,   0.9], [0.9,   1]]) 
psi[1, 2] = psi[2, 4] = torch.tensor([[0.1, 1.0], [1.0, 0.1]])
fi[1, 1]  = fi[3, 3]  = torch.tensor([[1  , 0.1], [0.1,   1]])


phi[1][2] = phi[3][4] = np.array([[1, 0.9], [0.9, 1]])
phi[2][3] = phi[3][5] = np.array([[0.1, 1], [1, 0.1]])
phi[2][2] = phi[4][4] = np.array([[1, 0.1], [0.1, 1]])

y3 = torch.tensor([[1], [0]]).float()
y1 = torch.tensor([[0], [1]]).float()

In [99]:
x4 = fi[3, 3]@y3
x5 = graph.x[4]
x3 = (psi[2, 3]@x4) * (psi[2, 4]@x5)
x2 = (fi[1, 1]@y1) * (psi[1, 2]@x3)
x1 = psi[0, 1]@x2
xx = torch.cat([x1, x2, x3, x4, x5], dim=1)
xx /xx.sum(axis=0)

tensor([[0.4944, 0.3936, 0.5141, 0.9091, 0.5000],
        [0.5056, 0.6064, 0.4859, 0.0909, 0.5000]])

In [98]:
n = 5
phi = [[None for i in range(n + 1)] for i in range(n + 1)]

phi[1][2] = phi[3][4] = np.array([[1, 0.9], [0.9, 1]])
phi[2][3] = phi[3][5] = np.array([[0.1, 1], [1, 0.1]])
phi[2][2] = phi[4][4] = np.array([[1, 0.1], [0.1, 1]])

belief = [None for i in range(n + 1)]

post_3 = phi[3][4].dot(phi[4][4].dot(np.array([0, 1])) + phi[3][5].dot(np.array([1, 1])))
post_2 = phi[2][2].dot(np.array([1, 0])) + phi[2][3].dot(post_3)
unnormalized = phi[1][2].dot(post_2)
belief[1] = unnormalized / np.sum(unnormalized)

In [77]:
belief, post_2/post_2.sum(), post_3/post_3.sum()

([None, array([0.50322818, 0.49677182]), None, None, None, None],
 array([0.5613355, 0.4386645]),
 array([0.49282297, 0.50717703]))